name: test coverage

on:
  push:
    branches: [master, dev]

jobs:
  cli-coverage-report:
    strategy:
      matrix:
        python-version: [ "3.11" ]
        os: [ ubuntu-latest ]
        r: [ release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install test dependencies
        run: if [ -f requirements/requirements-dev.txt ]; then pip install -r requirements/requirements-test.txt; fi

      - run: pip install .

      - name: Run tests
        run: coverage run -m pytest

      - name: build coverage
        run: coverage html -i

      - run: smokeshow upload htmlcov
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 80
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}