name: Flake

on:
  pull_request:
    branches: [main]


jobs:
  lint:
    name: flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.3.0
      with:
        select: E3,E4,E5,E7,W6,F,B,G0
        maxlinelength: 120
        repotoken: ${{ secrets.GITHUB_TOKEN }}
        exclude: .git,__pycache__,docs/source/conf.py,old,build,dist