name: Run pytests windows

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install all dependencies
      run: pip install -r requirements/requirements-all.txt

    - name: Install test dependencies
      run: pip install -r requirements/requirements-test.txt

    - name: Install package
      run: python -m pip install .

    - name: Run pytest tests
      run: pytest tests -v